### ISSUE TITLE
[text highlight] reconsider highlighting text only on double click

### ISSUE THREAD

**Issue by comanjoni** [zikicm/github-sublime#29]
Maybe it is enough to highlight selected text only when text is selected by double click or if while word is selected.
Let's discuss offline and update this issue with conclusion, that would be new request for update.

**Comment by zikicm** [comment]
For me, preferred behaviour would be to mimic Sublime. It does variable selection only on double click and I think users are used to it. Usually when someone selects something with mouse drag it is because of reading or to copy/paste. Also, if we decide to go this way, we could eliminate need for that busy wait from last code review.

**Comment by comanjoni** [comment]
I've checked how sublime behaves. It does highlighting only when whole word is selected and doesn't depend on how text is selected. Double-click is selecting word action that's why you are thinking that highlight appears only on that action. Try to select text with keyboard or by mouse down and move.
I'll change code to do highlight when whole word is selected for now and in next step I'll do research if it is possible to do that without busy-wait.
